[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3001"

# Railway 환경변수 (Railway 대시보드에서 설정)
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_ANON_KEY = "your-supabase-anon-key"
# BROWSER_SERVICE_API_KEY = "your-api-key"

[experimental]
incrementalBuildCaching = true
